### ISSUE TITLE
マインスイーパの表示が壊れる

### ISSUE THREAD

**Issue by KusaReMKN** [KusaReMKN/KusaReMKN.com#1]
https://twitter.com/kusaremkn/status/1669268358074884096

Windows 上の Chorome と Brave で確認
Firefox は試していない

Ubuntu 上の Chrome と Firefox では発生していないはず

**Comment by yude** [comment]
Windows 11 上の Chrome / Firefox で再現せず
![image](https://github.com/KusaReMKN/KusaReMKN.com/assets/14804458/14b7c904-6a49-44ab-bf67-13b0267a49c0)

**Comment by ghost** [comment]
普通に左クリック？

**Comment by KusaReMKN** [comment]
中クリックと左クリック（長押し）です

**Comment by yude** [comment]
Firefox on Windows 11 での現状（正直中クリックと左クリックを長押ししたときの挙動を知らないので動画を見て判断ください）
![2023-06-15_20-27-46_firefox_hC1lLnTu6K](https://github.com/KusaReMKN/KusaReMKN.com/assets/14804458/df306e77-e417-49fc-a1df-2e4584b73543)
カーソルの位置がズレてるのは録画ソフトのバグなので無関係す

**Comment by KusaReMKN** [comment]
カーソルの乗っているセル（中クリックのときはその周囲の 8 セルも）が凹み表示になる挙動が意図されているので問題なさそうに見えます

これ Chrome のバージョンのせいなのかな

**Comment by KusaReMKN** [comment]
Windows 10 上の Chrome Version 111.0.5563.65 (64 bit) だと正常に動くけど 114.0.5735.134 だと下の方にゴミが出るっぽい

**Comment by KusaReMKN** [comment]
アクセラレーションとか関係してるのかな、Chrome だと warning が出てた

![image](https://github.com/KusaReMKN/KusaReMKN.com/assets/48670724/f7d0d1bc-2507-44cb-9265-f0497f57e056)

**Comment by moyashim-25** [comment]
https://github.com/KusaReMKN/KusaReMKN.com/assets/108477615/50f9bd2f-3fe7-4dad-8d5f-d3c6e8cd9305

Windows 11 上
Chrome は最新の状態です
バージョン: 114.0.5735.134（Official Build） （64 ビット）

**Comment by moyashim-25** [comment]
![hoge](https://github.com/KusaReMKN/KusaReMKN.com/assets/108477615/22c24c1a-299e-4a41-8ee9-2ee866890d7d)

表示が乱れているとき、1マス開いていて周りが閉じていると、中クリックで開いていたマスが閉じちゃう

**Comment by KusaReMKN** [comment]
Windows 10 22H2 (19045.3208) で発生せず

Chrome は最新の状態です
バージョン: 115.0.5790.110（Official Build） （64 ビット）

これ以外の環境かつ最新のバージョンで発生しないなら close しようかな

**Comment by ghost** [comment]
エディション	Windows 11 Home
バージョン	22H2
インストール日	‎2023/‎06/‎17
OS ビルド	22621.1992
エクスペリエンス	Windows Feature Experience Pack 1000.22644.1000.0

Chrome: 115.0.5790.110 (64 bit)
Firefox: 115.0.3 (64 bit)
Edge: 115.0.1901.188 (64 bit)

該当する挙動なし

**Comment by KusaReMKN** [comment]
よくわからないけどもはや表示は壊れていないようなので close します
